name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download YOLOv8
      run: cd models; ./yolo.sh
    - name: Get libtorch
      run: ./build.sh
    - name: Build
      run: cargo build --examples --verbose
    - name: Run tests
      run: cargo test --verbose
